services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/geckoai/student-lottery-system-app:v1.0.0
  cleanup:
    image: registry.cn-hangzhou.aliyuncs.com/geckoai/student-lottery-system-app:v1.0.0  