services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/geckoai/student-lottery-system-app:v1.0.1
    ports:
        - "127.0.0.1:3000:3000"
  cleanup:
    image: registry.cn-hangzhou.aliyuncs.com/geckoai/student-lottery-system-app:v1.0.1
  proxy:
      profiles:
        - disabled